project:
  type: website

website:
  title: "<span class='animated-title'></span>"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - href: brown_algae.qmd
        text: why brown algae?
      - href: cv/cv.qmd
        text: download cv

format:
  html:
    theme: simplex
    css: styles.css
    fontsize: 1.1em
    linestretch: 1.7
    toc: true
    