project:
  type: website

website:
  title: "ꙩ ꙫ ө ꚛ ꙮ ༗"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - href: brown_algae.qmd
        text: why brown algae?

format:
  html:
    theme: simplex
    css: styles.css
    fontsize: 1.1em
    linestretch: 1.7
    toc: true
    